securitySchemes:
  cookieAuth:
    type: apiKey
    in: cookie
    name: ecommerceJaviCookie
    description: Enter access token from cookie

tags:
  - name: Products
    description: Operations related to products
paths:
  /api/products:
    get:
      tags:
        - Products
      summary: Retrieve all products
      description: Returns a list of products with optional filtering and pagination
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          type: integer
          format: int32
        - name: limit
          in: query
          description: Number of items per page
          required: false
          type: integer
          format: int32
        - name: category
          in: query
          description: Filter by category
          required: false
          type: string
        - name: available
          in: query
          description: Filter by availability
          required: false
          type: boolean
        - name: sortByPrice
          in: query
          description: Sort by price in ascending (asc) or descending (desc) order
          required: false
          type: string
          enum:
            - asc
            - desc
      responses:
        '200':
          description: A list of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        '500':
          description: Internal server error
    post:
      tags:
        - Products
      summary: Add a new product
      description: Add a new product to the database
      parameters:
        - in: body
          name: product
          description: The product to add
          required: true
          schema:
            $ref: '#/definitions/Product'
      requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/definitions/Product'
      security:
        - cookieAuth: []
      responses:
        '201':
          description: Product added successfully
        '400':
          description: Bad request - product with the same code already exists
        '403':
          description: Access denied - Insufficient privileges
        '500':
          description: Internal server error
  /api/products/{pid}:
    get:
      tags:
        - Products
      summary: Get a product by ID
      description: Returns a single product by its ID
      parameters:
        - name: pid
          in: path
          description: ID of the product to retrieve
          required: true
          type: string
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Product'
        '404':
          description: Product not found
        '500':
          description: Internal server error
    delete:
      tags:
        - Products
      summary: Delete a product
      description: Deletes a product by its ID
      parameters:
        - name: pid
          in: path
          description: ID of the product to delete
          required: true
          type: string
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Product removed correctly
        '404':
          description: Product not found
        '500':
          description: Internal server error
definitions:
  Product:
    type: object
    properties:
      title:
        type: string
        description: The name of the product
      description:
        type: string
        description: A description of the product
      price:
        type: number
        format: float
        description: The price of the product
      code:
        type: string
        description: Code of the product
      category:
        type: string
        description: The category of the product
      stock:
        type: integer
        description: The stock quantity of the product
      thumbnails:
        type: array
        description: Array of images of the product
        items:
          type: string